version: "3.9"
services:
  webserver:
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - cgi
      - db

  cgi:
    build:
      context: "backend"
      dockerfile: "phpWithPgsql.Dockerfile"  # Ensure this Dockerfile sets up PHP with PostgreSQL support
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pipikaka
      POSTGRES_DB: cpu_temperature
    volumes:
      - db_data:/var/lib/postgresql/data     # Persist data

  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db

volumes:
  db_data:
